version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_gui
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: